modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/refinedmods/refinedstorageaddons"
license = "MIT"
[[mods]]
modId = "refinedstorageaddons"
version = "${version}"
displayName = "Refined Storage Addons"
displayURL = "https://refinedmods.com/refined-storage/wireless-networking/wireless-crafting-grid.html"
authors = "Refined Mods"
description = '''
An addon mod for Refined Storage
'''
[[dependencies.refinedstorageaddons]]
modId = "refinedstorage"
versionRange = "[1.13.0-beta.1,)"
type = "REQUIRED"
ordering = "AFTER"
side = "BOTH"
